language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install .
  - pip install pytest
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=leansim setup.py test
after_success:
  - coveralls